// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1DssAucMKTq9PCCcxxl8ki83C0we_eEY',
    appId: '1:834405893568:web:f7240312eb044a3d7eb425',
    messagingSenderId: '834405893568',
    projectId: 'maize-care-fix',
    authDomain: 'maize-care-fix.firebaseapp.com',
    storageBucket: 'maize-care-fix.firebasestorage.app',
    measurementId: 'G-QLNHQ8T7KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVo0pY6XyzwmIm2YJU8uYZ7fRp_r5OWbM',
    appId: '1:834405893568:android:47b01056aa2d83187eb425',
    messagingSenderId: '834405893568',
    projectId: 'maize-care-fix',
    storageBucket: 'maize-care-fix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1MW71oa6i5j6ZzkpBYf59mGZbMp9j0M',
    appId: '1:834405893568:ios:ce01606c79dea3217eb425',
    messagingSenderId: '834405893568',
    projectId: 'maize-care-fix',
    storageBucket: 'maize-care-fix.firebasestorage.app',
    iosBundleId: 'com.example.maizecareFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1MW71oa6i5j6ZzkpBYf59mGZbMp9j0M',
    appId: '1:834405893568:ios:ce01606c79dea3217eb425',
    messagingSenderId: '834405893568',
    projectId: 'maize-care-fix',
    storageBucket: 'maize-care-fix.firebasestorage.app',
    iosBundleId: 'com.example.maizecareFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1DssAucMKTq9PCCcxxl8ki83C0we_eEY',
    appId: '1:834405893568:web:a3f05259c2b981697eb425',
    messagingSenderId: '834405893568',
    projectId: 'maize-care-fix',
    authDomain: 'maize-care-fix.firebaseapp.com',
    storageBucket: 'maize-care-fix.firebasestorage.app',
    measurementId: 'G-PL63DG2FMP',
  );
}
